apiVersion: v1
kind: ConfigMap
metadata:
  # you need to override the "version" in the Chart.yaml each time you make changes
  name: first-chart-configmap-{{.Chart.Version}}
data:
  port: "8080"
  {{if eq .Values.env "staging"}}
  allowTesting: "true"
  {{else}}
  allowTesting: "false"
  {{end}}